name: GitHub Actions Pipeline
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    container: node:16

    env:

    services:
      postgres:
        image: postgres:latest
        env:
          # optional (defaults to `postgres`)
          #POSTGRES_DB: postgres_db
          # required
          # optional (defaults to `5432`)
          # POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          # POSTGRES_USER: postgres_user
          DATABASE_URL: postgres://postgres:postgres_password@postgres:5432/postgres

          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Installing Dependencies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate dev --name testing --skip-generate

      - name: Compiling project
        run: npm run build

      - name: Run tests
        run: npm test
