name: GitHub Actions Pipeline
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Sets up node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Installing Dependencies
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Running tests
        run: npm test

      - run: echo "This job's status is ${{ job.status }}."
