name: GitHub Actions Pipeline
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Sets up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "Installing deps and running tests"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: echo "This job's status is ${{ job.status }}."
